global:
  resolve_timeout: 10s

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'telepush'

receivers:
  - name: 'telepush'
    webhook_configs:
    - url: 'https://telepush.dev/api/inlets/alertmanager/79a114' #URL с токеном после последнего слеша

  