groups:
  - name: containers_alerts
    rules:
      - alert: OneOfTheContainersFell
        expr: up == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.job }} is down on {{ $labels.instance }}"
          description: "{{ $labels.job }} has been down for more than 1 minute on {{ $labels.instance }}."
      
      - alert: ContainerCrash
        expr: count(count(container_last_seen) by (name)) != 14
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "Контейнер {{ $labels.container }} упал"
          description: "Контейнер {{ $labels.container }} не был замечен в течение последних 5 минут."